### ISSUE TITLE
Photos or samples of analytics

### ISSUE THREAD

**Issue by datatalking** [jazzband/django-analytical#144]
The fact that Django says it has analytics is good, but as a new user, there is no "this is what this analytics" look like so I am forced to read the code and hope that I understand what each module creates?

Couldn't you take a screenshot of what these python files create so we can see if this is what we are looking for?

**Comment by jcassee** [comment]
I'm not exactly sure yet what you mean. Are you saying the term "analytics" is not defined clearly? Or would you like an example of the template tag expansion? Maybe you could give a suggestion in the form of a pull request?

**Comment by bittner** [comment]
I believe, there is a fundamental misunderstanding in what django-analytical provides.

There are no dashboards and whatsoever. This is what [the services](https://github.com/jazzband/django-analytical#currently-supported-services) provide for evaluation that you subscribe to. Use _your_ account with _them_ to both set up analytics tracking and evaluate analytics results.

django-analytical is just a Python module to make integrating their _code snippets_ more clean. It does nothing else (if you want so). From the [README](https://github.com/jazzband/django-analytical#django-analytical-):

> This application hides the details of the different analytics services behind a generic interface, and keeps personal information and configuration out of the templates. Its goal is to make the basic set-up very simple, while allowing advanced users to customize tracking. Each service is set up as recommended by the services themselves, using an asynchronous version of the Javascript code if possible.

And no, you're not forced to read the code. There is a [very nice documentation](https://django-analytical.readthedocs.io/en/latest/tutorial.html) you're invited to consume.

**Comment by datatalking** [comment]
Hi Peter, 

Thanks for replying so quickly.

I’m misunderstanding this then.

I was thinking this was an analytics app for Django, but I’m… to me analytics means a dashboard of KPI.

Your documentation is elegant and efficient but if I can’t see the result of what it does I can’t understand what it does.

**Comment by bittner** [comment]
> if I can’t see the result of what it does I can’t understand what it does.

I understand this clearly. Could it be that you are maybe not the audience this module is trying to address? Python modules are for programmers, not data analysts.

It may be needed to rephrase the very first paragraph(s) of the README or documentation in a way that conveys the purpose of this module even more clearly. But how do you do that without limiting yourself to a specific target audience?

Django is clearly for web developers (not content editors or business users). It's a framework for programmers. And all Python modules are so, too.

Anyway, if you can get your head around the workings of this Python module (which is called "a Django app", which is really more or less plain Python code) and then have an idea of making the intro paragraphs more clear, let us know!

Screenshots won't cut it in this case, because it's all about Python code and Django template code (which is some sort of HTML). It would be taking screenshots of our development environments. Of course, someone could do a video on Django + analytics good practices, but I'm not sure if then we're making people laugh about us -- for exaggerating.  :smile:

**Comment by datatalking** [comment]
Its entirely possible that I am trying to put a round peg in a square hole.

This seems less of an analytics GUI and more of a headless interface for 3rd party API’s ?

I think what I am looking for is more like

https://www.fiverr.com/yawyaw213/build-your-django-dashboards
or
https://medium.com/@hakibenita/how-to-turn-django-admin-into-a-lightweight-dashboard-a0e0bbf609ad

Thanks for your help.

**Comment by jcassee** [comment]
Yes, exactly, this project is for integrating, for example, Google Analytics and not building your own dashboards.

**Comment by bittner** [comment]
> https://www.fiverr.com/yawyaw213/build-your-django-dashboards

There you go! _That_ person may want to use django-analytical. Under the hood. And he may not even tell you about it.
